exclude: /migrations/
default_language_version:
  python: python3.9
repos:
  - repo: local
    hooks:
      - id: add-trailing-comma
        name: add-trailing-comma
        entry: add-trailing-comma
        args: [--py36-plus]
        language: python
        types: [python]
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        require_serial: true
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        require_serial: true
