services:
  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_DB=wdt
      - POSTGRES_USER=wdt
      - POSTGRES_PASSWORD=password
  wdt-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://wdt:password@db:5432/wdt
      - SECRET_KEY=secret
    depends_on:
      - db
    ports:
      - 8000
