[tool.poetry]
name = "wdt"
version = "0.1.0"
description = ""
authors = ["Zac Tolley <zac@thetolleys.com>"]

[tool.poetry.dependencies]
python = "^3.9.1"
Django = "^3.1.6"
django-environ = "^0.4.5"
psycopg2 = "^2.8.6"
ariadne = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
