# Generated by Django 3.1.6 on 2021-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
