# Generated by Django 3.1.5 on 2021-01-31 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('display_order', models.IntegerField()),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.section')),
            ],
            options={
                'db_table': 'section_item',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='items',
            field=models.ManyToManyField(through='menu.SectionItem', to='menu.Item'),
        ),
        migrations.AddField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.item')),
            ],
            options={
                'db_table': 'item_ingredient',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(through='menu.ItemIngredient', to='menu.Ingredient'),
        ),
        migrations.AddField(
            model_name='item',
            name='sections',
            field=models.ManyToManyField(through='menu.SectionItem', to='menu.Section'),
        ),
        migrations.AddConstraint(
            model_name='sectionitem',
            constraint=models.UniqueConstraint(fields=('section_id', 'item_id'), name='unique_section_and_item'),
        ),
        migrations.AddConstraint(
            model_name='itemingredient',
            constraint=models.UniqueConstraint(fields=('item_id', 'ingredient_id'), name='unique_item_and_ingredient'),
        ),
    ]
