name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: wdt
          POSTGRES_PASSWORD: password
          POSTGRES_USER: wdt
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: secret
      DATABASE_URL: postgres://wdt:password@localhost:5432/wdt
      DEBUG: True

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenvs-path: ~/.virtualenvs

    - name: Cache Poetry virtualenv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Flake8
      run: poetry run flake8

    - name: Black code format
      run: poetry run black . --check

    - name: Run migrations
      run: poetry run python manage.py migrate

    - name: Tests
      run: poetry run pytest --cov --junit-xml=test-output/test-output.xml --cov-report xml:test-output/coverage.xml
      env:
        DJANGO_SETTINGS_MODULE: wdt.settings
