name: Test and Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: wdt
          POSTGRES_PASSWORD: password
          POSTGRES_DB: wdt
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Poetry
      uses: snok/install-poetry@v1.1.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenv-path: ~/.virtualenvs

    - name: Cache Poetry virtualenv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}

    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Flake8
      run: poetry run flake8

    - name: Black code format
      run: poetry run black . --check

    - name: Tests
      env:
        DATABASE_URL: postgres://wdt:password@postgres/wdt
        DEBUG: True
        DJANGO_SETTINGS_MODULE: wdt.settings
        SECRET_KEY: secret
      run: poetry run pytest --cov
