# Generated by Django 3.1.6 on 2021-02-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='owner_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
