# Generated by Django 3.1.7 on 2021-02-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210205_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='owner_id',
        ),
    ]
